<?php require('template/loggedInHeader.phtml');


?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>


        <?php foreach
        ($view->userDataSet as $userData)
        {
              echo '<h3> Your Email: ' .  $userData->getEmail()  . '</h3>';
              echo '<h3> Your Real Name: ' .  $userData->getRealName() . '</h3>';
        } ?>
    <input type="submit" name="addItem" value="Click To put item up for sale">

</form>

<?php require('template/footer.phtml') ?>
