<?php

if(isset($_SESSION["loginEmail"]))
{
    require('template/loggedInHeader.phtml');
}
else
{
    require('template/header.phtml');
}
?>


<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <table class="table table-hover">
       <thead>
       <tr><th>BidID</th><th>Lot</th><th>Seller</th><th>Amount Bid</th></tr>


       </thead>   
    <tbody>
        <?php foreach
        ($view->bidDataSet as $bidData)
        {

              echo '<tr> <td>' .  $bidData->getBidID()  . '</td>';
              echo ' <td>' .  $bidData->getLot()  . '</td>';
              echo ' <td>' .  $bidData->getUserID()  . '</td>';
              echo ' <td>' .  $bidData->getBidPrice()  . '</td>';
              echo '<td> <input type="submit" name="view"   value="' . $bidData->getLot() . '"> </td> </tr>';

        }
        ?>
    </tbody>
  </table>  
</form>

<?php require('template/footer.phtml') ?>
